name: atom
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: A hackable text editor for the 21st Century.
description: |
  Atom is a free and open source text editor that is modern,
  approachable, and hackable to the core.

grade: stable
confinement: classic

architectures:
  - build-on: amd64

parts:
  gnome:
    plugin: nil
    build-packages:
      - software-properties-common
    override-pull: |
      add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
      apt -y update
      apt -y upgrade

  atom:
    after:
      - gnome
    plugin: dump
    source: https://atom.io/download/deb
    source-type: deb
    override-build: |
      DEB_API="https://atom.io/download/deb"
      DEB_URL=$(curl -w "%{url_effective}\n" -I -L -s -S "${DEB_API}" -o /dev/null)
      VERSION=$(echo "${DEB_URL}" | cut -d'/' -f4 | tr -d 'v')
      echo $VERSION > $SNAPCRAFT_STAGE/version
      snapcraftctl build
      sed -i 's|Icon=atom|Icon=/usr/share/pixmaps/atom\.png|g' usr/share/applications/atom.desktop
    build-packages:
      - curl
    stage-packages:
      - fcitx-frontend-gtk3
      - libappindicator3-1
      - libasound2
      - libcurl3-gnutls
      - libgconf-2-4
      - libgtk-3-0
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
  launcher:
    plugin: dump
    source: files/
    prepare: |
      chmod +x bin/launcher

apps:
  atom:
    command: bin/launcher ${SNAP}/usr/share/atom/atom
    desktop: usr/share/applications/atom.desktop
  apm:
    command: bin/launcher ${SNAP}/usr/bin/apm
