name: atom
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: A hackable text editor for the 21st Century.
description: |
  Atom is a free and open source text editor that is modern,
  approachable, and hackable to the core.
base: core18

grade: stable
confinement: classic

architectures:
  - build-on: amd64

parts:
  bsi-trigger: # A non-built part, only used to trigger builds in build.snapcraft.io on upstream changes
    plugin: nil
    source: https://github.com/atom/atom.git
  libappindicator:
    after:
      - desktop-gnome-platform
    plugin: nil
    stage-packages:
      - libappindicator3-1
    prime:
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdbusmenu*.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libappindicator*.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libindicator*.so*

  desktop-gnome-platform:
    build-packages:
    - build-essential
    - libgtk-3-dev
    make-parameters:
    - FLAVOR=gtk3
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk

  atom:
    after:
      - desktop-gnome-platform
    plugin: dump
    source: https://atom.io/download/deb
    source-type: deb
    override-build: |
      set -x 
      DEB_API="https://atom.io/download/deb"
      DEB_URL=$(curl -w "%{url_effective}\n" -I -L -s -S "${DEB_API}" -o /dev/null)
      VERSION=$(echo "${DEB_URL}" | cut -d'/' -f4 | tr -d 'v')
      echo $VERSION > $SNAPCRAFT_STAGE/version
      snapcraftctl build
      pwd
      ls -l usr/share/applications
      grep Icon $SNAPCRAFT_PART_INSTALL/usr/share/applications/atom.desktop
      sed -i 's|Icon=atom|Icon=${SNAP}/usr/share/pixmaps/atom\.png|g' $SNAPCRAFT_PART_INSTALL/usr/share/applications/atom.desktop
      grep Icon $SNAPCRAFT_PART_INSTALL/usr/share/applications/atom.desktop
    build-packages:
      - curl
    stage-packages:
      - fcitx-frontend-gtk3
      - libappindicator3-1
      - libasound2
      - libcurl3-gnutls
      - libgconf-2-4
      - libgtk-3-0
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
  launcher:
    plugin: dump
    source: files/
    override-build: |
      snapcraftctl build
      chmod +x bin/launcher

apps:
  atom:
    command: bin/launcher ${SNAP}/usr/share/atom/atom
    desktop: usr/share/applications/atom.desktop
    environment:
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1

  apm:
    command: bin/launcher ${SNAP}/usr/bin/apm
